version: "3"

tasks:
  install:
    cmds:
      - rm -rf build
      - conan install . --output-folder=build --build=missing

  build:
    deps: [install]
    dir: ./build
    cmds:
      - cmake .. -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
      - cmake --build .

  run:
    deps: [build]
    dir: ./build
    cmds:
      - ./conan-demo
